version: '3.9'
services:
  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - postgresql-db
    env_file:
      - .env

  postgresql-db:
    image: postgres:16
    platform: linux/x86_64
    container_name: postgresql-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgresql-todo-db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  postgresql-todo-db-data: